platform :ios, '15.0'
# source 'https://github.com/CocoaPods/Specs.git'

target 'shic' do
  use_frameworks!

  # Pods for shic
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseStorage'
  pod 'SDWebImageSwiftUI'
  pod 'TinkoffASDKCore'
  pod 'TinkoffASDKUI'
  pod 'TinkoffASDKYandexPay'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Update build configurations for all targets
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
    end
    
    # Modify compiler flags for BoringSSL-GRPC
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
